### ISSUE TITLE
cucumber.options tags are ignored in serenityCucumberVersion 1.0.22 and cucumberVersion 4.8.0

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-cucumber4#15]
When using Serenity with Cucumber-JVM and adding a tag in the .feature file above the Feature or Scenario definition (e.g. @api:rest), then it is not possible to run that test by itself using gradle.

gradlew clean test -Dcucumber.options="--tags @api:rest" 

The issue can be reproduced with
    serenityCoreVersion = '2.0.89'
    serenityCucumberVersion = '1.0.22'
    cucumberVersion = '4.8.0'

**Comment by cliviu** [comment]
This should be fixed with the next version...

**Comment by ilzul** [comment]
Thanks a lot ! Looking forward to test that on my test project

**Comment by s2oBCN** [comment]
> When using Serenity with Cucumber-JVM and adding a tag in the .feature file above the Feature or Scenario definition (e.g. @api:rest), then it is not possible to run that test by itself using gradle.
> 
> gradlew clean test -Dcucumber.options="--tags @api:rest"
> 
> The issue can be reproduced with
> serenityCoreVersion = '2.0.89'
> serenityCucumberVersion = '1.0.22'
> cucumberVersion = '4.8.0'

Also, with the deprecated cucumber.api.CucumberOptions the runner can find the features, but with the new implementation io.cucumber.junit.CucumberOptions no features are found.

**Comment by wakaleo** [comment]
Should be fixed in 1.0.28

**Comment by ilzul** [comment]
work like a charm. thanks a lot !
