### ISSUE TITLE
serenity-cucumber4 project migration to serenity-cucumber5?

### ISSUE THREAD

**Issue by revfran** [serenity-bdd/serenity-cucumber4#28]
Hello!

I'm using serenity-cucumber4 at the moment with no major issues, mainly for rest-assured.

I wonder if based on README.md information, and to keep my project healthy and prepare for future updates if I should move to serenity-cucumber5.

Is it stable enough?

Is it backwards compatible?

Any kind of reference to obtain more information about cucumber4/cucumber5 roadmap and features to have a bigger picture?

Best regards.

**Comment by cliviu** [comment]
hi @revfran . Here are all the cucumber changes that you need : https://github.com/cucumber/cucumber-jvm/blob/main/CHANGELOG.md . As far as I know , serenity-cucumber5 is backwards compatible  with serenity-cucumber4. 
Is as much as stable as serenity-cucumber5.
serenity-cucumber6 will come soon.  stay tuned :-)
