### ISSUE TITLE
"timeout" not working "withTimeoutOf(Duration.of(timeout, SECONDS))" for shouldNotContainText() and shouldContainText() Methods

### ISSUE THREAD

**Issue by bzsharm** [serenity-bdd/serenity-cucumber4#34]
**Error Description:-**  "timeout" not working **"withTimeoutOf(Duration.of(timeout, SECONDS))"** for **shouldNotContainText()** and **shouldContainText();**

While using "withTimeoutOf(Duration.of(timeout, SECONDS))" for method "shouldNotContainText(String)/shouldContainText(String)" ,"timeout" duration is getting
overridden by **webdriver.wait.for.timeout = 30000** from the **serenity.properties** file instead of "timeout" parsed in the custom method created .

**Version Details:-**

<serenity.version>2.1.1</serenity.version>
<cucumber.version>4.2.0</cucumber.version>

**Example:-**

        public void waitUntilElementContainsText(WebElementFacade elem, String strTxt,int timeout){
        elem.withTimeoutOf(Duration.of(timeout, SECONDS)).shouldNotContainText(strTxt);

    }

**Comment by wakaleo** [comment]
This is expected behaviour. You need to put withTimeoutOf() BEFORE the element variable, otherwise the timeout will be applied the first time the variable is used, ie before withTimeoutOf is called.

**Comment by bzsharm** [comment]
WebElementFacade elem ;

elem.withTimeoutOf(Duration.of(timeout, SECONDS))

Something like this right?

**Comment by bzsharm** [comment]
I used it in the same way that you advised , this is how the method looks 

    **public void waitUntilElementContainsText(WebElementFacade elem, String strTxt,int timeout){
    elem.withTimeoutOf(Duration.of(timeout, SECONDS)).shouldNotContainText(strTxt);

}**

**Comment by bzsharm** [comment]
@wakaleo any thoughts

**Comment by wakaleo** [comment]
withTimeoutOf(Duration.of(timeout, SECONDS))...

**Comment by wakaleo** [comment]
It only applies to operations following the "withTimeoutOf(), not the object itself.

**Comment by bzsharm** [comment]
thanks for your response @wakaleo My Intention here is to make the "element wait till it contains the particular String / Text".
(WebElementFacade) ! 
Please advise

**Comment by wakaleo** [comment]
```
withTimeoutOf(Duration.ofSeconds(10)).waitFor(ExpectedConditions.textToBe(By.cssSelector("#my-element"), "Expected Text"));
```

**Comment by bzsharm** [comment]
@wakaleo thanks for the response John !
