### ISSUE TITLE
Question: is the --threads option of cucumber4 actually supported?

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-cucumber4#4]
We've now migrated our serenity/cucumber-jvm tests the cucumber4 and running them with --threads.
While this works generally great, I just seen a strange issue:
For a failing test the BDD report reported a step to be failing for a scenario which the test was not actually part of!

serenity-core 2.0.48, serenity-cucumber4:1.0.12, cucumber-jvm 4.2.0

**Comment by wakaleo** [comment]
No, if I recall correctly the events that Cucumber sends don’t work for reporting purposes (yet?)

**Comment by kutzi** [comment]
hmm, okay

**Comment by kutzi** [comment]
Is that fixable? If I remember correctly there are some options you have in cucumber4 to receive the events in the correct order, right?

**Comment by wakaleo** [comment]
I haven’t had time to look yet

**Comment by kutzi** [comment]
I'd say somehow cucumber.runtime.formatter.SerenityReporter needs to be modified that most/all of the internal stuff is handled thread-local: stepQueues, tags, currentScenarioId

**Comment by wakaleo** [comment]
All the reporting logic is already thread-local - feel free to have a look though.

**Comment by kutzi** [comment]
SerenityReporter has e.g. a single stepQueue which is e.g. used to determine the current step.
I guess that needs to be a thread-local queue.

I can have a look and convert everything - which appears to need it - to thread-local, but in the end I'm not really known with that code.

**Comment by wakaleo** [comment]
See what you can do and I will take a look - handing th current step should indeed be threadlocal.

**Comment by kutzi** [comment]
See https://github.com/serenity-bdd/serenity-cucumber4/pull/5

**Comment by wakaleo** [comment]
Fixed in 1.0.28
