### ISSUE TITLE
serenity-cucumber4 version 1.0.12 fails to run

### ISSUE THREAD

**Issue by SiKing** [serenity-bdd/serenity-cucumber4#8]
Using serenity-cucumber4, version 1.0.12, running from Maven, fails to run with:
`java.lang.NoClassDefFoundError: cucumber/runner/TimeServiceEventBus`

This is because one of the downstream projects - serenity-screenplay - brings in cucumber-core version 2.4.0.

Workaround is to explicitly bring in cucumber-core 4.2.0 to be same version as other cucumber components.

**Comment by wakaleo** [comment]
See https://johnfergusonsmart.com/getting-started-with-serenity-bdd-and-cucumber-4/ - this is required to maintain backward compatibility with Cucumber 2.x

**Comment by SiKing** [comment]
Hmmm, I thought all this could be handled just in the serenity-cucumber4 pom.xml.

Thanx for the response.
